spring:
  application:
    name: API_Gateway_SaiVishnuRamakrishnan
  cloud:
    gateway:
      routes:
        - id: HOSPITAL_MICROSERVICE_SAIVISHNURAMAKRISHNAN
          uri: lb://HOSPITAL_MICROSERVICE_SAIVISHNURAMAKRISHNAN
          predicates:
            - Path=/hospitalFeign/**
        - id: SPRING_API_SAIVISHNURAMAKRISHNAN
          uri: lb://SPRING_API_SAIVISHNURAMAKRISHNAN
          predicates:
            - Path=/hospital/**
  server:
    port: 1111
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
  jwt:
    secret: username
